project:
  type: website
  output-dir: docs

website:
  title: "RIntro2024"
  favicon: /images/RIntro2024.png
  navbar:
    logo: /images/RIntro2024.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

